version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:7f:65:73:50:f2:06:3c:2b:6f:54:0a:32:20:ab:c2"
      - checkout 
      - run:
          name: Configure SSH agent
          command: |
            ssh-add -D
            ssh-add ~/.ssh/id_rsa
            cat ~/.ssh/id_rsa
            echo "breaker"
            cat /home/circleci/.ssh/id_rsa
      - run:
          name: Clone react repo
          command: |
            GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
            echo $GIT_SSH_COMMAND
            git clone git@github.com:punit1109/punit-private.git
            pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm build
    