version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # - add_ssh_keys:
      #     fingerprints:
      #       - "51:17:f0:58:2f:eb:e7:2f:f6:7b:5a:3b:74:69:11:11" 
      # - run:
      #     name: Configure SSH agent
      #     command: |
      #       ssh-add -D
      #       ssh-add ~/.ssh/id_rsa
      #       cat ~/.ssh/id_rsa
      #       echo "breaker"
      #       cat /home/circleci/.ssh/id_rsa
      - add_ssh_keys:
          fingerprints:
            - "86:98:dc:4f:e9:80:67:8a:31:25:d6:45:a7:ce:93:4e"
      - run:
          name: Clone react repo 
          command: |
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_86:98:dc:4f:e9:80:67:8a:31:25:d6:45:a7:ce:93:4e'
            git clone --progress --verbose punitlakhwani11@gmail.com:punit1109/punit-private.git ~/punit-private
            pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm build
    