version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
 

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
    
  publish:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Clone react repo
          command: |
            pwd
            ls /home/circleci/
            git clone https://github.com/punit1109/react-app.git
            ls -al 
            dir=$(pwd)
            echo "$dir"
      - run:
          name: Build container
          command: |
            pwd
            ls -al 
            ls -al /home/circleci/
            docker build -t punit-react --build-arg DIRECTORY=react-app .
            docker images
            docker ps 

workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - publish