version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - run:
          name: Clone react repo
          command: |
            git clone https://github.com/punit1109/react-app.git
            pwd
            ls -al

      - run:
          name: Build container
          command: |
            docker build -t punit-react .
            docker images
            docker ps 

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm start
    